#! /usr/bin/env ruby
require 'rexml/document'

case $axis=ARGV.shift
when 'X','x'
	$coords = %w<y3 z3 x3>
when 'Y','y'
	$coords = %w<z3 x3 y3>
when 'Z','z'
	$coords = %w<x3 y3 z3>
else
	raise 'Unacceptable axis `%s\'!' % $axis
end

translation = ARGV.shift.to_f
$stderr.puts 'translate %f along the %s-axis' % [translation, $axis]

doc = REXML::Document.new($stdin)
doc.get_elements('molecule/atomArray/atom').collect do |atom|
	#translation axis last
	x,y,z = $coords.collect{|l| atom.attribute(l).to_s.to_f}
	z    += translation
	[$coords,[x,y,z]].transpose.each do |l,v|
		atom.attributes[l] = v
	end
end

puts doc
